"""alter table hosts

Revision ID: 16632e34d99a
Revises: 3beae5d763a6
Create Date: 2017-07-20 11:05:03.873070

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '16632e34d99a'
down_revision = '3beae5d763a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.drop_column('host_ips')
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('host_ips', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
