"""create script manage

Revision ID: 340dc028230c
Revises: 16632e34d99a
Create Date: 2017-07-21 10:11:16.848980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340dc028230c'
down_revision = '16632e34d99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_manage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('script_manage')
    # ### end Alembic commands ###
