"""add field to task

Revision ID: 3beae5d763a6
Revises: cceb0603bca4
Create Date: 2017-07-19 18:10:03.596786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3beae5d763a6'
down_revision = 'cceb0603bca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('host_ips', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('variables', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'variables')
    op.drop_column('tasks', 'host_ips')
    # ### end Alembic commands ###
