"""alert script manage table

Revision ID: 820ec5df2fbb
Revises: 340dc028230c
Create Date: 2017-07-21 13:47:02.772678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820ec5df2fbb'
down_revision = '340dc028230c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_manages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('script_manage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['script_manage_id'], ['script_manages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('script_manage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_manage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('script_variables')
    op.drop_table('script_manages')
    # ### end Alembic commands ###
