"""drop column hostid from inventory

Revision ID: 88a33062aab6
Revises: 9dd4bb59610a
Create Date: 2017-08-14 11:28:37.870825

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '88a33062aab6'
down_revision = '9dd4bb59610a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('cmps', 'hostid')
    with op.batch_alter_table('cmps') as batch_op:
        batch_op.drop_column('hostid')
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmps', sa.Column('hostid', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
