"""add alias to inventory

Revision ID: 9dd4bb59610a
Revises: 4d968a25d137
Create Date: 2017-08-10 13:40:32.423435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd4bb59610a'
down_revision = '4d968a25d137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventorys', sa.Column('alias', sa.String(length=50), nullable=True))
    with op.batch_alter_table('inventorys') as batch_op:
        batch_op.drop_column('alias_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventorys', sa.Column('alias_name', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('inventorys', 'alias')
    # ### end Alembic commands ###
