"""add column hostid to inventory

Revision ID: bb5ae14b008e
Revises: 88a33062aab6
Create Date: 2017-08-14 11:30:25.086834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5ae14b008e'
down_revision = '88a33062aab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmp_items', sa.Column('hostid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmp_items', 'hostid')
    # ### end Alembic commands ###
