"""add mid_host_group_inventorys table

Revision ID: d5a229313781
Revises: 2dd8a66abb0b
Create Date: 2017-08-03 11:01:56.287084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a229313781'
down_revision = '2dd8a66abb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mid_host_group_inventorys',
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.Column('hostid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupid'], ['host_groups.groupid'], ),
    sa.ForeignKeyConstraint(['hostid'], ['inventorys.hostid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mid_host_group_inventorys')
    # ### end Alembic commands ###
